backend/backend/urls.py
from django.urls import path, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('comics.urls')),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

backend/urls.py
from django.urls import path, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('comics.urls')),
                  path('comments/', include('comments.urls')),
                  path('users/', include('users.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

comics/urls.py
from django.urls import path, include

from . import views

app_name = 'comics'
urlpatterns = [
    path('', views.index, name='index'),
    path('comics/', include([
        path('', views.comics_list, name='comic_list'),

        path('<int:comic_id>/', views.comic_details, name='comic_detail'),
        path('<int:comic_id>/chapter-<int:chapter_id>/', views.chapter_details, name='chapter_detail'),
        path('<int:comic_id>/delete/', views.delete_comic, name='delete_comic'),
        path('<int:comic_id>/status/<str:status_id>/', views.change_comic_status, name='change_comic_status'),
        path('add_new_comic/', views.new_comic, name='add_new_comic'),

        path('<int:comic_id>/new_chapter', views.new_chapter, name='add_new_chapter'),
        path('delete_chapter/<int:chapter_id>/', views.delete_chapter, name='delete_chapter'),

        path('like_chapter/<int:chapter_id>', views.like_chapter, name='like_chapter'),
        path('rate_comic/<int:comic_id>/<int:rating>', views.rate_comic, name='rate_comic'),
        path('buy_chapter/<int:chapter_id>', views.buy_chapter, name='buy_chapter'),
        path('toggle_bookmark/<int:comic_id>', views.bookmark_comic, name='toggle_bookmark'),
        path('delete_history_entry/<int:entry_id>', views.delete_history_entry, name='delete_history_entry'),
    ])),
]

comments/urls.py
from django.urls import path, include

from . import views

app_name = 'comments'

urlpatterns = [
    path('add/<int:chapter_id>', views.add_comment, name='add_comment'),
    path('delete/<int:comment_id>', views.delete_comment, name='delete_comment'),
]

users/urls.py
from django.urls import path, include

from users import views

app_name = 'users'

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('signup/', views.register, name='signup'),
    path('settings/', views.settings, name='settings'),
    path('buy_coins/', views.market, name='buy_coins'),
    path('change_username/', views.change_username, name='change_username'),
    path('change_password/', views.change_password, name='change_password'),
    path('become_creator/', views.become_creator, name='become_creator'),
]

backend/comics/models.py
import time

from django.db import models
from django.contrib.auth import models as auth_models
from dynamic_image.fields import DynamicImageField

from . import managers


# Create your models here.


class User(auth_models.AbstractUser):
    coins = models.IntegerField(default=0)
    is_creator = models.BooleanField(default=False)

    email = models.EmailField(max_length=255, unique=True)

    objects = managers.UserManager()

    def __str__(self):
        return self.username


class Genre(models.Model):
    name = models.CharField(unique=True, max_length=50)

    def __str__(self):
        return self.name


class Comic(models.Model):
    ONGOING = 'O'
    HIATUS = 'H'
    COMPLETED = 'C'
    CANCELLED = 'D'
    STATUS = [
        (ONGOING, 'ONGOING'),
        (HIATUS, 'HIATUS'),
        (COMPLETED, 'COMPLETED'),
        (CANCELLED, 'CANCELLED'),
    ]

    title = models.CharField(unique=True, max_length=255)
    creator = models.ForeignKey(to=User, on_delete=models.CASCADE)
    genres = models.ManyToManyField(to=Genre)
    watches = models.PositiveBigIntegerField(default=0)
    follows = models.PositiveBigIntegerField(default=0)
    rating = models.FloatField(default=0)
    status = models.CharField(choices=STATUS, default=ONGOING, max_length=1)
    summary = models.TextField()
    thumbnail = DynamicImageField()
    cover = DynamicImageField()

    def __str__(self):
        return self.title

    def get_upload_to(self, field_name):
        class_name = self.__class__.__name__.lower()
        instance_name = self.title.lower().replace(' ', '-')
        return f'{class_name}/{instance_name}'


class Chapter(models.Model):
    title = models.CharField(max_length=255)
    comic = models.ForeignKey(to=Comic, on_delete=models.CASCADE)
    pub_date = models.DateTimeField(auto_now_add=True)
    likes = models.PositiveBigIntegerField(default=0)
    cost = models.PositiveIntegerField(default=50)

    models.UniqueConstraint(fields=['title', 'comic'], name='comic_chapter')

    def __str__(self):
        return f'{self.comic.title} - {self.title}'


class ChapterImage(models.Model):
    image = DynamicImageField()
    chapter = models.ForeignKey(to=Chapter, on_delete=models.CASCADE)

    models.UniqueConstraint(fields=['image', 'chapter'], name='chapter_image')

    def __str__(self):
        return self.image.name

    def get_upload_to(self, field_name):
        chapter_name = self.chapter.title.lower().replace(' ', '-')
        comic_name = self.chapter.comic.title.lower().replace(' ', '-')
        return f'chapter/{comic_name}/{chapter_name}'


class ReadHistory(models.Model):
    chapter = models.ForeignKey(to=Chapter, on_delete=models.CASCADE)
    user = models.ForeignKey(to=User, on_delete=models.CASCADE)
    date = models.DateField(auto_now_add=True)

    def __str__(self):
        return f'{self.user} - {self.chapter} - {self.date}'


class BuyList(models.Model):
    chapter = models.ForeignKey(to=Chapter, on_delete=models.CASCADE)
    user = models.ForeignKey(to=User, on_delete=models.CASCADE)
    date = models.DateField(auto_now_add=True)

    models.UniqueConstraint(fields=['user', 'chapter'], name='bought_chapter')

    def __str__(self):
        return f'{self.user} - {self.chapter} - {self.date}'

comics/forms.py
from django import forms

from .models import Comic, Genre, Chapter, ChapterImage


class ComicForm(forms.ModelForm):
    title = forms.CharField(max_length=200, required=True, help_text='Enter Comic Title', widget=forms.TextInput())
    summary = forms.CharField(required=True, help_text='Enter Comic Description', widget=forms.Textarea())
    cover = forms.ImageField(required=True, help_text='Upload Comic Cover')
    genres = forms.ModelMultipleChoiceField(
        queryset=Genre.objects.all(), required=True, help_text='Select Genres',
        widget=forms.CheckboxSelectMultiple(
            attrs={'class': 'form-check-input'}
        )
    )

    class Meta:
        model = Comic
        fields = ['title', 'summary', 'cover', 'genres']


class ChapterForm(forms.ModelForm):
    chapter_number = forms.IntegerField(required=True, help_text='Enter Chapter Number', min_value=0)

    class Meta:
        model = Chapter
        fields = ['chapter_number']


class ChapterImageForm(forms.ModelForm):
    images = forms.ImageField(
        required=True,
        help_text='Upload Chapter Images',
        widget=forms.ClearableFileInput(attrs={'multiple': True})
    )

    class Meta:
        model = ChapterImage
        fields = ['images']

backend/comics/views/views.py
from django.shortcuts import render, HttpResponse, Http404, redirect
from django.http import HttpRequest
from django.urls import reverse_lazy

from django.contrib.auth.decorators import login_required
from django.views.generic.edit import CreateView

from ..forms import UserForm
from ..models import Comic, Chapter, User, Library, Rating, BuyList, ChapterImage, Like, Comment
import json


def index(request) -> HttpResponse:
    latest_chapters = Chapter.objects.order_by('-pub_date')[:10]
    latest_chapters = tuple(latest_chapters)
    latest_updates = []

    for chapter in latest_chapters:
        comic = Comic.objects.get(pk=chapter.comic.id)
        latest_updates.append(comic)

    latest_updates = set(latest_updates)
    context = {
        'latest_updates': latest_updates
    }

    return render(request, 'comics/index.html', context)


def comics_list(request) -> HttpResponse:
    comics = None
    try:
        for key, param in request.GET.lists():
            if key == 'g':
                comics = Comic.objects.filter(genre__in=param)
            elif key == 'name':
                comics = Comic.objects.get(title__contains=param)
    except Comic.DoesNotExist:
        ...

    if comics:
        comics = set(comics)

    print(comics)
    context = {
        'comics': comics
    }

    return render(request, 'comics/series.html', context)


def comic_details(request, comic_id) -> HttpResponse:
    try:
        comic = Comic.objects.get(pk=comic_id)
    except Comic.DoesNotExist:
        raise Http404("Comic does not exist")

    try:
        author_name = User.objects.get(pk=comic.creator_id).username
    except User.DoesNotExist:
        author_name = "Unknown"

    genres = comic.genre.all()[:4]

    chapters = Chapter.objects.filter(comic=comic_id).order_by('chapter_num')

    bookmark = None
    rating = None
    buy_list = None
    if request.user.is_authenticated:
        try:
            bookmark = Library.objects.get(user=request.user.id, comic=comic.id)
        except Library.DoesNotExist:
            ...

        try:
            rating = Rating.objects.get(user=request.user.id, comic=comic.id)
        except Rating.DoesNotExist:
            ...

        bought = BuyList.objects.filter(user=request.user.id, chapter__comic_id=comic.id)
        if bought:
            buy_list = [chapter.chapter_id for chapter in bought]

    context = {
        'comic': comic,
        'author_name': author_name,
        'genres': genres,
        'bookmark': bookmark,
        'rating': rating,
        'ratingRange': range(1, 11),
        'chapters': chapters,
        'buy_list': buy_list
    }

    return render(request, 'comics/comic.html', context)


@login_required(login_url='comics:login')
def add_bookmark(request: HttpRequest, comic_id: int) -> HttpResponse:
    if request.method == 'POST':
        user_id = request.user.id
        comic = Comic.objects.get(pk=comic_id)

        try:
            library = Library.objects.get(user=user_id, comic=comic_id)
            library.delete()
            comic.follows -= 1
        except Library.DoesNotExist:
            library = Library.objects.create(user_id=user_id, comic_id=comic_id)
            comic.follows += 1

        comic.save()

        return HttpResponse(comic.follows, status=200)
    return HttpResponse(status=403)


@login_required(login_url='comics:login')
def add_rating(request, comic_id, rating) -> HttpResponse:
    if request.method == 'POST':
        user_id = request.user.id
        comic = Comic.objects.get(pk=comic_id)

        message = ""
        try:
            rating_obj = Rating.objects.get(user_id=user_id, comic=comic)
            if rating == 0:
                rating_obj.delete()
                message = "d"
            else:
                rating_obj.rating = rating
                rating_obj.save()
                message = "u"

        except Rating.DoesNotExist:
            rating_obj = Rating.objects.create(user_id=user_id, comic=comic, rating=rating)
            message = "a"

        comic_ratings = Rating.objects.filter(comic=comic_id)
        values = list(comic_ratings.values('rating'))
        val_list = [x['rating'] for x in values]
        if val_list:
            avg_rating = sum(val_list) / len(val_list)
            comic.rating = avg_rating
        else:
            comic.rating = 0
        comic.save()

        data = {
            'message': message,
            'rating': comic.rating
        }

        return HttpResponse(json.dumps(data), status=200)
    return HttpResponse(status=403)


def register(request):
    if request.method == 'GET':
        form = UserForm()
        context = {
            'form': form
        }
        return render(request, 'registration/signup.html', context)

    if request.method == 'POST':
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('comics:login')
        else:
            context = {
                'form': form,
            }
            return render(request, 'registration/signup.html', context)


@login_required(login_url='comics:login')
def profile(request):
    ...


def user_details(request, user_id):
    ...


@login_required(login_url='comics:login')
def settings(request):
    ...


@login_required(login_url='comics:login')
def logout(request):
    ...


@login_required(login_url='comics:login')
def buy_chapter(request, chapter_id):
    ...


@login_required(login_url='comics:login')
def chapter_details(request, comic_id, chapter_id):
    try:
        chapter = Chapter.objects.get(comic_id=comic_id, chapter_num=chapter_id)
    except Chapter.DoesNotExist:
        return Http404("Chapter does not exist")

    images = ChapterImage.objects.filter(chapter=chapter)

    chapter_list = Chapter.objects.filter(comic_id=comic_id)

    prev_chapter = None
    next_chapter = None
    if chapter.chapter_num > 0:
        prev_chapter = Chapter.objects.get(comic_id=comic_id, chapter_num=chapter.chapter_num - 1)

    if chapter.chapter_num < chapter_list.count() - 1:
        next_chapter = Chapter.objects.get(comic_id=comic_id, chapter_num=chapter.chapter_num + 1)

    like = None
    try:
        like = Like.objects.get(user_id=request.user.id, chapter=chapter)
    except Like.DoesNotExist:
        ...

    comments = Comment.objects.filter(chapter=chapter)

    context = {
        'chapter': chapter,
        'images': images,
        'prev_chapter': prev_chapter,
        'next_chapter': next_chapter,
        'chapter_list': chapter_list,
        'like': like,
        'comments': comments
    }

    return render(request, 'comics/chapter.html', context)


@login_required(login_url='comics:login')
def like_chapter(request, chapter_id):
    if request.method == 'POST':
        user_id = request.user.id
        chapter = Chapter.objects.get(pk=chapter_id)

        try:
            chapter_like = Like.objects.get(user_id=user_id, chapter_id=chapter_id)
            chapter_like.delete()
            chapter.likes -= 1
        except Like.DoesNotExist:
            chapter_like = Like.objects.create(user_id=user_id, chapter_id=chapter_id)
            chapter.likes += 1

        chapter.save()

        return HttpResponse(chapter.likes, status=200)


@login_required(login_url='comics:login')
def add_comment(request, chapter_id):
    if request.method == 'POST':
        user_id = request.user.id
        try:
            chapter = Chapter.objects.get(pk=chapter_id)
        except Chapter.DoesNotExist:
            return Http404("Chapter does not exist")

        reply_id = request.POST.get('reply_to')
        body = request.POST.get('comment')

        if reply_id:
            comment = Comment.objects.create(user_id=user_id, chapter=chapter, reply_id=reply_id, body=body)
        else:
            comment = Comment.objects.create(user_id=user_id, chapter=chapter, body=body)

        return HttpResponse(status=200)


@login_required(login_url='comics:login')
def delete_comment(request, comment_id):
    if request.method == 'POST':

        try:
            comment = Comment.objects.get(pk=comment_id)
        except Comment.DoesNotExist:
            return Http404("Comment does not exist")
        if comment.user_id == request.user.id:
            comment.delete()
            return HttpResponse(status=200)

        return HttpResponse(status=403)

comics/templates/comics/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">

	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
	      integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous"/>
	<link href="{% static 'fontawesomefree/css/all.min.css' %}" rel="stylesheet" type="text/css">


	<link href="{% static 'comics/css/base.css' %}" rel="stylesheet" type="text/css"/>

	{% block head %}
	{% endblock %}
</head>
<body>

{% include "comics/components/navigation.html" %}

<main class="container">
	{% block main %}
	{% endblock %}
	{% include 'comics/components/backToTopBtn.html' %}
</main>
</body>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2"
        crossorigin="anonymous"></script>
<script type="text/javascript" src="https://code.jquery.com/jquery-1.7.1.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/js-cookie@3.0.1/dist/js.cookie.min.js"></script>
<script>
  const csrftoken = Cookies.get('csrftoken');
</script>
{% block javascript %}

{% endblock %}
</html>

comics/templates/comics/chapter.html
{% extends 'comics/base.html' %}
{% load static %}

{% block head %}
	<title>{{ chapter.comic.title }} - Chapter {{ chapter.chapter_num }}</title>
{% endblock %}

{% block main %}
	<div class="container d-flex flex-row justify-content-between px-5 mt-3">
		<div class="d-flex flex-row">
			<a href="{% url 'comics:comic_detail' comic_id=chapter.comic_id %}" class="me-2">
				<button class="btn btn-dark">
					All chapters
				</button>
			</a>
			<div class="dropdown">
				<button class="btn btn-dark dropdown-toggle" id="chapterListDropdown" data-bs-toggle="dropdown"
				        aria-expanded="false">Select chapter
				</button>
				<ul class="dropdown-menu" aria-labelledby="chapterListDropdown">

					{% for c in chapter_list %}
						<li class="dropdown-item">
							<a class="text-decoration-none text-dark"
							   href="{% url 'comics:chapter_detail' comic_id=chapter.comic_id chapter_id=c.chapter_num %} ">
								Chapter {{ c.chapter_num }}
							</a>
						</li>
					{% endfor %}
				</ul>
			</div>

		</div>
		{% csrf_token %}
		{% if like %}
			<button class="btn btn-dark" id="likeBtn" onclick="removeLike({{ chapter.id }})">
		<span>
			{{ chapter.likes }}
		</span>
				<i id="heartIcon" class="fas fa-heart"></i>
			</button>
		{% else %}
			<button class="btn btn-dark" id="likeBtn" onclick="addLike({{ chapter.id }})">
		<span>
			{{ chapter.likes }}
		</span>
				<i id="heartIcon" class="far fa-heart"></i>
			</button>
		{% endif %}

		<div class="d-flex flex-row">
			{% if prev_chapter != None %}
				<a href="{% url 'comics:chapter_detail' comic_id=chapter.comic_id chapter_id=prev_chapter.chapter_num %}">
					<button class="btn btn-dark">
						Prev
					</button>
				</a>
			{% else %}
				<a>
					<button class="btn btn-dark disabled">
						Prev
					</button>
				</a>
			{% endif %}
			{% if next_chapter != None %}
				<a href="{% url 'comics:chapter_detail' comic_id=chapter.comic_id chapter_id=next_chapter.chapter_num %}"
				   class="ms-2">
					<button class="btn btn-dark">
						Next
					</button>
				</a>
			{% else %}
				<a class="ms-2">
					<button class="btn btn-dark disabled">
						Next
					</button>
				</a>
			{% endif %}
		</div>

	</div>
	<div class="container align-items-center d-flex flex-column">
		{% for image in images %}
			<img src="/media/{{ image.image }}" alt="Chapter-{{ chapter.chapter_num }}"/>
		{% endfor %}
	</div>

	<div id="commentSection" class="container-fluid w-75 mt-5">
		<h3>Comments</h3>
		<form id="commentForm">
			{% csrf_token %}
			<div id="replyBox" style="display: none">
				<a onclick="removeReply()" class="btn">
					<i class="fas fa-xmark"></i>
				</a>
				<span id="replyTo"></span>
			</div>
			<input type="hidden" name="comment_id" id="replyId" placeholder="Name"/>
			<div class="input-group mb-3">
				<input id="newComment" type="text" class="form-control" placeholder="Leave a comment..."
				       aria-label="Leave a comment..." aria-describedby="button-addon2" required>
				<button class="btn btn-outline-dark" type="submit" id="button-addon2">Post</button>
			</div>
		</form>

		<div id="comments">
			<ul class="list-unstyled">
				{% for comment in comments %}
					{% if comment.reply == None %}
						<li class="mb-3" id="comment_{{ comment.id }}">
							<div class='card card-body'>
								<div class='d-flex flex-row align-items-end'>
									<h5 class='card-title mb-0 me-2'>{{ comment.user.username }}</h5>
									<span class='card-subtitle'> - {{ comment.created_on }}</span>

								</div>
								{% if comment.user.id == user.id %}
									<div style="position: absolute; right: 20px;">
										<a class='btn btn-outline-dark' onclick='deleteComment({{ comment.id }})'>
											<i class="fas fa-xmark"></i>
										</a>
									</div>
								{% endif %}
								<div class='card-text'>{{ comment.body }}</div>
								<div class="">
									<a class='btn btn-outline-dark'
									   onclick='postReply({{ comment.id }}, "{{ comment.user.username }}")'>Reply</a>
								</div>

							</div>
							<ul id="comment_{{ comment.id }}_replies" class="list-unstyled ms-4">
								{% for reply in comment.reply_to.all %}
									<li id="comment_{{ reply.id }}">
										<div class='card card-body'>
											<div class='d-flex flex-row align-items-end'>
												<i class="fa-solid fa-arrow-turn-up me-2"
												   style="transform: rotateY(180deg); padding-bottom: 6px"></i>
												<h5 class='card-title mb-0 me-2'>{{ reply.user.username }}</h5>
												<span class='card-subtitle'> - {{ reply.created_on }}</span>
											</div>
											{% if reply.user.id == user.id %}
												<div style="position: absolute; right: 20px;">
													<a class='btn btn-outline-dark'
													   onclick='deleteComment({{ reply.id }})'>
														<i class="fas fa-xmark"></i>
													</a>
												</div>
											{% endif %}
											<div class='card-text'>{{ reply.body }}</div>
										</div>
									</li>
								{% endfor %}
							</ul>
						</li>
					{% endif %}
				{% endfor %}
			</ul>
		</div>
	</div>
{% endblock %}


{% block javascript %}
	<script src="{% static 'comics/js/like.js' %}" type="text/javascript"></script>
	<script src="{% static 'comments/js/comment.js' %}" type="text/javascript"></script>
	<script>
      $('#commentForm').submit((e) => {
        e.preventDefault();

        $.ajax({
          url: "{% url 'comments:add_comment' chapter_id=chapter.id %}",
          type: 'POST',
          headers: {
            'X-CSRFToken': csrftoken
          },
          dataType: 'json',
          data: {
            comment: $('#newComment').val(),
            reply_to: $('#replyId').val()
          },
          success: (data) => {
            location.reload();
          }
        });
      });
	</script>
{% endblock %}

comics/templates/comics/index.html
{% extends "comics/base.html" %}
{% load static %}
{% block head %}
	<link href="{% static 'comics/css/card.css' %}" rel="stylesheet"/>
	<link href="{% static 'comics/css/index.css' %}" rel="stylesheet"/>
	<title>Comics</title>
{% endblock %}
{% block title %} Comics {% endblock %}

{% block main %}
	<h1 class="new_uploads">
		New uploads
	</h1>
	<section class="card_list mb-4">

		{% for comic in latest_updates %}
			{% include "comics/components/card.html" %}
		{% endfor %}
	</section>
	<nav aria-label="Page navigation example" class="">
		<ul class="pagination justify-content-center">
			{% if prev %}
				<li class="page-item">
					{% else %}
				<li class="page-item disabled">
			{% endif %}
			<a class="page-link" href="{% url 'comics:index' %}?page={{ prev_page }}" aria-label="Previous">
				<span aria-hidden="true">Previous</span>
			</a>
			</li>

			{% if next %}
				<li class="page-item ">
					{% else %}
				<li class="page-item disabled">
			{% endif %}
			<a class="page-link" href="{% url 'comics:index' %}?page={{ next_page }}" aria-label="Next">
				<span aria-hidden="true">Next</span>
			</a>
			</li>
		</ul>
	</nav>

{% endblock %}

comics/templates/comics/new_chapter.html
{% extends 'comics/base.html' %}
{% load widget_tweaks %}

{% block head %}
	<title>New Comic</title>
{% endblock %}

{% block main %}
	<div class="container mt-5 w-75">
		<h1>Add new chapter to: {{ comic.title }}</h1>
		<form action="{% url 'comics:add_new_chapter' comic_id=comic.id %}" method="post" enctype="multipart/form-data">
			{% csrf_token %}
			<div class="mb-3">
				<label for="id_chapter_number" class="form-label">{{ ch_form.chapter_number.label }}</label>
				{% render_field ch_form.chapter_number class+="form-control" placeholder="Chapter number" %}
				{{ ch_form.chapter_number.errors }}
			</div>
			<div class="mb-3">
				<label for="id_images" class="form-label">{{ img_form.images.label }}</label>
				{% render_field img_form.images class+="form-control" placeholder="Images" %}
				{{ img_form.images.errors }}
			</div>

			<button type="submit" class="btn btn-dark">Add new chapter</button>
		</form>
	</div>
{% endblock %}

{% block javascript %}
{% endblock %}

comics/templates/comics/new_comic.html
{% extends 'comics/base.html' %}
{% load widget_tweaks %}


{% block head %}
	<title>New Comic</title>
{% endblock %}

{% block main %}
	<div class="container w-75 mt-5">
		<h1>New Comic</h1>
		<form action="{% url 'comics:add_new_comic' %}" method="post" enctype="multipart/form-data">
			{% csrf_token %}
			<div class="mb-3">
				<label for="id_title" class="form-label">{{ form.title.label }}</label>
				{% render_field form.title class+="form-control" placeholder="Title" %}
				{{ form.title.errors }}
			</div>
			<div class="mb-3">
				<label for="id_summary" class="form-label">{{ form.summary.label }}</label>
				{% render_field form.summary class+="form-control" placeholder="Summary" %}
				{{ form.summary.errors }}
			</div>

			<div class="mb-3">
				<label class="form-label" for="id_cover">{{ form.cover.label }}</label>
				{% render_field form.cover class+="form-control" placeholder="Cover" %}
				{{ form.cover.errors }}
			</div>

			<div class="mb-3 dropend">
				<button class="dropdown-toggle btn btn-secondary " type="button" id="dropdownMenuButton"
				        data-bs-toggle="dropdown" aria-expanded="false" data-bs-auto-close="outside">
					{{ form.genres.label }}
				</button>
				<ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
					{% for genre in form.genres %}
						<li>
							<div class="dropdown-item">
								{{ genre }}
							</div>
						</li>
					{% endfor %}
				</ul>
				{{ form.genres.errors }}
			</div>
			<button type="submit" class="btn btn-dark">Add Comic</button>
		</form>
	</div>
{% endblock %}

{% block javascript %}
{% endblock %}