backend/backend/urls.py
from django.urls import path, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('comics.urls')),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

backend/urls.py
from django.urls import path, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('comics.urls')),
                  path('comments/', include('comments.urls')),
                  path('users/', include('users.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

comics/urls.py
from django.urls import path, include

from . import views

app_name = 'comics'
urlpatterns = [
    path('', views.index, name='index'),
    path('comics/', include([
        path('', views.comics_list, name='comic_list'),

        path('<int:comic_id>/', views.comic_details, name='comic_detail'),
        path('<int:comic_id>/chapter-<int:chapter_id>/', views.chapter_details, name='chapter_detail'),
        path('<int:comic_id>/delete/', views.delete_comic, name='delete_comic'),
        path('<int:comic_id>/status/<str:status_id>/', views.change_comic_status, name='change_comic_status'),
        path('add_new_comic/', views.new_comic, name='add_new_comic'),

        path('<int:comic_id>/new_chapter', views.new_chapter, name='add_new_chapter'),
        path('delete_chapter/<int:chapter_id>/', views.delete_chapter, name='delete_chapter'),

        path('like_chapter/<int:chapter_id>', views.like_chapter, name='like_chapter'),
        path('rate_comic/<int:comic_id>/<int:rating>', views.rate_comic, name='rate_comic'),
        path('buy_chapter/<int:chapter_id>', views.buy_chapter, name='buy_chapter'),
        path('toggle_bookmark/<int:comic_id>', views.bookmark_comic, name='toggle_bookmark'),
        path('delete_history_entry/<int:entry_id>', views.delete_history_entry, name='delete_history_entry'),
    ])),
]

users/urls.py
from django.urls import path, include

from users import views

app_name = 'users'

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('signup/', views.register, name='signup'),
    path('settings/', views.settings, name='settings'),
    path('buy_coins/', views.market, name='buy_coins'),
    path('change_username/', views.change_username, name='change_username'),
    path('change_password/', views.change_password, name='change_password'),
    path('become_creator/', views.become_creator, name='become_creator'),
]

backend/comics/models.py
import time

from django.db import models
from django.contrib.auth import models as auth_models
from dynamic_image.fields import DynamicImageField

from . import managers


# Create your models here.


class User(auth_models.AbstractUser):
    coins = models.IntegerField(default=0)
    is_creator = models.BooleanField(default=False)

    email = models.EmailField(max_length=255, unique=True)

    objects = managers.UserManager()

    def __str__(self):
        return self.username


class Genre(models.Model):
    name = models.CharField(unique=True, max_length=50)

    def __str__(self):
        return self.name


class Comic(models.Model):
    ONGOING = 'O'
    HIATUS = 'H'
    COMPLETED = 'C'
    CANCELLED = 'D'
    STATUS = [
        (ONGOING, 'ONGOING'),
        (HIATUS, 'HIATUS'),
        (COMPLETED, 'COMPLETED'),
        (CANCELLED, 'CANCELLED'),
    ]

    title = models.CharField(unique=True, max_length=255)
    creator = models.ForeignKey(to=User, on_delete=models.CASCADE)
    genres = models.ManyToManyField(to=Genre)
    watches = models.PositiveBigIntegerField(default=0)
    follows = models.PositiveBigIntegerField(default=0)
    rating = models.FloatField(default=0)
    status = models.CharField(choices=STATUS, default=ONGOING, max_length=1)
    summary = models.TextField()
    thumbnail = DynamicImageField()
    cover = DynamicImageField()

    def __str__(self):
        return self.title

    def get_upload_to(self, field_name):
        class_name = self.__class__.__name__.lower()
        instance_name = self.title.lower().replace(' ', '-')
        return f'{class_name}/{instance_name}'


class Chapter(models.Model):
    title = models.CharField(max_length=255)
    comic = models.ForeignKey(to=Comic, on_delete=models.CASCADE)
    pub_date = models.DateTimeField(auto_now_add=True)
    likes = models.PositiveBigIntegerField(default=0)
    cost = models.PositiveIntegerField(default=50)

    models.UniqueConstraint(fields=['title', 'comic'], name='comic_chapter')

    def __str__(self):
        return f'{self.comic.title} - {self.title}'


class ChapterImage(models.Model):
    image = DynamicImageField()
    chapter = models.ForeignKey(to=Chapter, on_delete=models.CASCADE)

    models.UniqueConstraint(fields=['image', 'chapter'], name='chapter_image')

    def __str__(self):
        return self.image.name

    def get_upload_to(self, field_name):
        chapter_name = self.chapter.title.lower().replace(' ', '-')
        comic_name = self.chapter.comic.title.lower().replace(' ', '-')
        return f'chapter/{comic_name}/{chapter_name}'


class ReadHistory(models.Model):
    chapter = models.ForeignKey(to=Chapter, on_delete=models.CASCADE)
    user = models.ForeignKey(to=User, on_delete=models.CASCADE)
    date = models.DateField(auto_now_add=True)

    def __str__(self):
        return f'{self.user} - {self.chapter} - {self.date}'


class BuyList(models.Model):
    chapter = models.ForeignKey(to=Chapter, on_delete=models.CASCADE)
    user = models.ForeignKey(to=User, on_delete=models.CASCADE)
    date = models.DateField(auto_now_add=True)

    models.UniqueConstraint(fields=['user', 'chapter'], name='bought_chapter')

    def __str__(self):
        return f'{self.user} - {self.chapter} - {self.date}'

comics/forms.py
from django import forms

from .models import Comic, Genre, Chapter, ChapterImage


class ComicForm(forms.ModelForm):
    title = forms.CharField(max_length=200, required=True, help_text='Enter Comic Title', widget=forms.TextInput())
    summary = forms.CharField(required=True, help_text='Enter Comic Description', widget=forms.Textarea())
    cover = forms.ImageField(required=True, help_text='Upload Comic Cover')
    genres = forms.ModelMultipleChoiceField(
        queryset=Genre.objects.all(), required=True, help_text='Select Genres',
        widget=forms.CheckboxSelectMultiple(
            attrs={'class': 'form-check-input'}
        )
    )

    class Meta:
        model = Comic
        fields = ['title', 'summary', 'cover', 'genres']


class ChapterForm(forms.ModelForm):
    chapter_number = forms.IntegerField(required=True, help_text='Enter Chapter Number', min_value=0)

    class Meta:
        model = Chapter
        fields = ['chapter_number']


class ChapterImageForm(forms.ModelForm):
    images = forms.ImageField(
        required=True,
        help_text='Upload Chapter Images',
        widget=forms.ClearableFileInput(attrs={'multiple': True})
    )

    class Meta:
        model = ChapterImage
        fields = ['images']

backend/comics/views/views.py
from django.shortcuts import render, HttpResponse, Http404, redirect
from django.http import HttpRequest
from django.urls import reverse_lazy

from django.contrib.auth.decorators import login_required
from django.views.generic.edit import CreateView

from ..forms import UserForm
from ..models import Comic, Chapter, User, Library, Rating, BuyList, ChapterImage, Like, Comment
import json


def index(request) -> HttpResponse:
    latest_chapters = Chapter.objects.order_by('-pub_date')[:10]
    latest_chapters = tuple(latest_chapters)
    latest_updates = []

    for chapter in latest_chapters:
        comic = Comic.objects.get(pk=chapter.comic.id)
        latest_updates.append(comic)

    latest_updates = set(latest_updates)
    context = {
        'latest_updates': latest_updates
    }

    return render(request, 'comics/index.html', context)


def comics_list(request) -> HttpResponse:
    comics = None
    try:
        for key, param in request.GET.lists():
            if key == 'g':
                comics = Comic.objects.filter(genre__in=param)
            elif key == 'name':
                comics = Comic.objects.get(title__contains=param)
    except Comic.DoesNotExist:
        ...

    if comics:
        comics = set(comics)

    print(comics)
    context = {
        'comics': comics
    }

    return render(request, 'comics/series.html', context)


def comic_details(request, comic_id) -> HttpResponse:
    try:
        comic = Comic.objects.get(pk=comic_id)
    except Comic.DoesNotExist:
        raise Http404("Comic does not exist")

    try:
        author_name = User.objects.get(pk=comic.creator_id).username
    except User.DoesNotExist:
        author_name = "Unknown"

    genres = comic.genre.all()[:4]

    chapters = Chapter.objects.filter(comic=comic_id).order_by('chapter_num')

    bookmark = None
    rating = None
    buy_list = None
    if request.user.is_authenticated:
        try:
            bookmark = Library.objects.get(user=request.user.id, comic=comic.id)
        except Library.DoesNotExist:
            ...

        try:
            rating = Rating.objects.get(user=request.user.id, comic=comic.id)
        except Rating.DoesNotExist:
            ...

        bought = BuyList.objects.filter(user=request.user.id, chapter__comic_id=comic.id)
        if bought:
            buy_list = [chapter.chapter_id for chapter in bought]

    context = {
        'comic': comic,
        'author_name': author_name,
        'genres': genres,
        'bookmark': bookmark,
        'rating': rating,
        'ratingRange': range(1, 11),
        'chapters': chapters,
        'buy_list': buy_list
    }

    return render(request, 'comics/comic.html', context)


@login_required(login_url='comics:login')
def add_bookmark(request: HttpRequest, comic_id: int) -> HttpResponse:
    if request.method == 'POST':
        user_id = request.user.id
        comic = Comic.objects.get(pk=comic_id)

        try:
            library = Library.objects.get(user=user_id, comic=comic_id)
            library.delete()
            comic.follows -= 1
        except Library.DoesNotExist:
            library = Library.objects.create(user_id=user_id, comic_id=comic_id)
            comic.follows += 1

        comic.save()

        return HttpResponse(comic.follows, status=200)
    return HttpResponse(status=403)


@login_required(login_url='comics:login')
def add_rating(request, comic_id, rating) -> HttpResponse:
    if request.method == 'POST':
        user_id = request.user.id
        comic = Comic.objects.get(pk=comic_id)

        message = ""
        try:
            rating_obj = Rating.objects.get(user_id=user_id, comic=comic)
            if rating == 0:
                rating_obj.delete()
                message = "d"
            else:
                rating_obj.rating = rating
                rating_obj.save()
                message = "u"

        except Rating.DoesNotExist:
            rating_obj = Rating.objects.create(user_id=user_id, comic=comic, rating=rating)
            message = "a"

        comic_ratings = Rating.objects.filter(comic=comic_id)
        values = list(comic_ratings.values('rating'))
        val_list = [x['rating'] for x in values]
        if val_list:
            avg_rating = sum(val_list) / len(val_list)
            comic.rating = avg_rating
        else:
            comic.rating = 0
        comic.save()

        data = {
            'message': message,
            'rating': comic.rating
        }

        return HttpResponse(json.dumps(data), status=200)
    return HttpResponse(status=403)


def register(request):
    if request.method == 'GET':
        form = UserForm()
        context = {
            'form': form
        }
        return render(request, 'registration/signup.html', context)

    if request.method == 'POST':
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('comics:login')
        else:
            context = {
                'form': form,
            }
            return render(request, 'registration/signup.html', context)


@login_required(login_url='comics:login')
def profile(request):
    ...


def user_details(request, user_id):
    ...


@login_required(login_url='comics:login')
def settings(request):
    ...


@login_required(login_url='comics:login')
def logout(request):
    ...


@login_required(login_url='comics:login')
def buy_chapter(request, chapter_id):
    ...


@login_required(login_url='comics:login')
def chapter_details(request, comic_id, chapter_id):
    try:
        chapter = Chapter.objects.get(comic_id=comic_id, chapter_num=chapter_id)
    except Chapter.DoesNotExist:
        return Http404("Chapter does not exist")

    images = ChapterImage.objects.filter(chapter=chapter)

    chapter_list = Chapter.objects.filter(comic_id=comic_id)

    prev_chapter = None
    next_chapter = None
    if chapter.chapter_num > 0:
        prev_chapter = Chapter.objects.get(comic_id=comic_id, chapter_num=chapter.chapter_num - 1)

    if chapter.chapter_num < chapter_list.count() - 1:
        next_chapter = Chapter.objects.get(comic_id=comic_id, chapter_num=chapter.chapter_num + 1)

    like = None
    try:
        like = Like.objects.get(user_id=request.user.id, chapter=chapter)
    except Like.DoesNotExist:
        ...

    comments = Comment.objects.filter(chapter=chapter)

    context = {
        'chapter': chapter,
        'images': images,
        'prev_chapter': prev_chapter,
        'next_chapter': next_chapter,
        'chapter_list': chapter_list,
        'like': like,
        'comments': comments
    }

    return render(request, 'comics/chapter.html', context)


@login_required(login_url='comics:login')
def like_chapter(request, chapter_id):
    if request.method == 'POST':
        user_id = request.user.id
        chapter = Chapter.objects.get(pk=chapter_id)

        try:
            chapter_like = Like.objects.get(user_id=user_id, chapter_id=chapter_id)
            chapter_like.delete()
            chapter.likes -= 1
        except Like.DoesNotExist:
            chapter_like = Like.objects.create(user_id=user_id, chapter_id=chapter_id)
            chapter.likes += 1

        chapter.save()

        return HttpResponse(chapter.likes, status=200)


@login_required(login_url='comics:login')
def add_comment(request, chapter_id):
    if request.method == 'POST':
        user_id = request.user.id
        try:
            chapter = Chapter.objects.get(pk=chapter_id)
        except Chapter.DoesNotExist:
            return Http404("Chapter does not exist")

        reply_id = request.POST.get('reply_to')
        body = request.POST.get('comment')

        if reply_id:
            comment = Comment.objects.create(user_id=user_id, chapter=chapter, reply_id=reply_id, body=body)
        else:
            comment = Comment.objects.create(user_id=user_id, chapter=chapter, body=body)

        return HttpResponse(status=200)


@login_required(login_url='comics:login')
def delete_comment(request, comment_id):
    if request.method == 'POST':

        try:
            comment = Comment.objects.get(pk=comment_id)
        except Comment.DoesNotExist:
            return Http404("Comment does not exist")
        if comment.user_id == request.user.id:
            comment.delete()
            return HttpResponse(status=200)

        return HttpResponse(status=403)

comics/templates/comics/components/backToTopBtn.html
{% load static %}
<link rel="stylesheet" href="{% static 'comics/css/backToTopBtn.css' %}">
<button
		type="button"
		class="btn btn-dark btn-floating btn-lg"
		id="backToTopBtn"
>
	<i class="fas fa-arrow-up"></i>
</button>

<script type="text/javascript" src="{% static 'comics/js/backToTopBtn.js' %}"></script>

comics/templates/comics/components/card.html
<div class="card" id="{{ comic.id }}">
	<a href="{% url 'comics:comic_detail' comic_id=comic.id %}">
		<img
				alt="image"
				src="/media/{{ comic.cover }}"
				class="cover"
		/>
	</a>
	<div class="lower_half">
		<a href="{% url 'comics:comic_detail' comic_id=comic.id %}" class="text-decoration-none">
			<h5 class="title">{{ comic.title }}</h5>
		</a>
		<div class="info">
			<div class="rating_box">
				<span>{{ comic.rating }}</span>
				<i class="fa-solid fa-star star"></i>
			</div>
			<div class="status_box">
				{% if comic.status == 'O' %}
					<i class="fa-solid fa-circle status_dot ongoing"></i>
					<span class="status">Ongoing</span>
				{% elif comic.status == 'H' %}
					<i class="fa-solid fa-circle status_dot hiatus"></i>
					<span class="status">Hiatus</span>
				{% elif comic.status == 'C' %}
					<i class="fa-solid fa-circle status_dot completed"></i>
					<span class="status">Completed</span>
				{% elif comic.status == 'D' %}
					<i class="fa-solid fa-circle status_dot cancelled"></i>
					<span class="status">Cancelled</span>
				{% endif %}
			</div>
		</div>
	</div>
</div>

comics/templates/comics/components/modal.html
<div class="modal fade" id="buyModal" aria-labelledby="buyModalLabel" aria-hidden="true">
	<div class="modal-dialog modal-dialog-centered">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title">Buy chapter</h5>
				<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
			</div>
			<div class="modal-body">
				<p>Click buy to buy this chapter</p>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-outline-dark" data-bs-dismiss="modal">Close</button>
				<form id="buyForm" method="POST">
					{% csrf_token %}
					<input id="buyValue" type="hidden" name="chapter_id" value="">
					<button type="submit" class="btn btn-dark">Buy</button>
				</form>
			</div>
		</div>

	</div>
</div>

<div class="modal fade" id="anonUserModal" aria-labelledby="anonUserModalLabel" aria-hidden="true">
	<div class="modal-dialog modal-dialog-centered">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title">Login required</h5>
				<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
			</div>
			<div class="modal-body">
				<p>To buy this chapter you are required to login first.</p>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-outline-dark" data-bs-dismiss="modal">Close</button>
				<a href="{% url 'users:login' %}">
					<button type="button" class="btn btn-dark">Login</button>
				</a>
			</div>
		</div>

	</div>
</div>

comics/templates/comics/components/navigation.html
<header class="p-3 bg-dark text-white">
	<div class="container">
		<div class="d-flex flex-wrap align-items-center justify-content-center">
			<a href="{% url 'comics:index' %}" class="d-flex align-items-center  me-3 text-white text-decoration-none">
				<span class="fs-4">Home</span>
			</a>

			<ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
				<li><a href="{% url 'comics:comic_list' %}" class="nav-link px-2 text-secondary">Series</a></li>
			</ul>

			<form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" role="search" action="{% url 'comics:comic_list' %}">
				<label>
					<input type="search" class="form-control form-control-dark text-white bg-dark"
					       placeholder="Search..."
					       name="p"/>
				</label>
			</form>
			{% if user.is_authenticated %}
				<div class="dropdown text-end">
					<a class="d-block link-light text-decoration-none dropdown-toggle" id="dropdownUser1"
					   data-bs-toggle="dropdown" aria-expanded="false">
						<span class="fs-6">Hi, {{ user.username }}</span>
						<i class="fa-regular fa-circle-user fs-3"></i>
					</a>
					<ul class="dropdown-menu text-small" aria-labelledby="dropdownUser1">
						{% if user.is_creator %}
							<li>
								<span class="dropdown-item-text">Creator</span>
							</li>
						{% endif %}
						<li>
							<a href="{% url 'users:buy_coins' %}" class="dropdown-item">
								{{ user.coins }}
								<i class="fas fa-coins"></i>
							</a>
						</li>
						<li><a class="dropdown-item" href="{% url 'users:settings' %}">User settings</a></li>
						<li>
							<hr class="dropdown-divider">
						</li>
						<li><a class="dropdown-item" href="{% url 'users:logout' %}">Sign out</a></li>
					</ul>
				</div>
			{% else %}
				<div class="text-end">
					<a href="{% url 'users:login' %}" class="text-decoration-none">
						<button type="button" class="btn btn-outline-light me-2">
							Sign in
						</button>
					</a>
					<a href="{% url 'users:signup' %}" class="text-decoration-none">
						<button type="button" class="btn btn-warning">
							Sign up
						</button>
					</a>

				</div>
			{% endif %}
		</div>
	</div>
</header>